# Generated by Django 5.1.1 on 2024-10-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id_habito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia', models.PositiveIntegerField(default=1)),
                ('titulo_recordatorio', models.CharField(default='No olvides que tienes un objetivo', max_length=64)),
                ('mensaje_recordatorio', models.CharField(default='Recuerda que cada día se vuelve más fácil, lo dificil es hacerlo todos los días.', max_length=255)),
                ('notificar', models.BooleanField(default=True)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.objetivo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habito')),
            ],
        ),
        migrations.CreateModel(
            name='Categorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoria')),
                ('id_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habito')),
            ],
            options={
                'unique_together': {('id_habito', 'id_categoria')},
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField()),
                ('id_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.objetivo')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('dia__gte', 1), ('dia__lte', 31)), name='dia_valid_range')],
                'unique_together': {('id_objetivo', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('id_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.habito')),
            ],
            options={
                'unique_together': {('id_habito', 'hora')},
            },
        ),
    ]
