# Generated by Django 5.1.1 on 2024-10-07 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoria'),
        ),
        migrations.DeleteModel(
            name='Categorizado',
        ),
    ]
