# Generated by Django 5.1.1 on 2024-10-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_habito_id_categoria_delete_categorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoria'),
        ),
    ]
